name: day
version: 0.5.0
description: >-
  A date library Day.js in dart.
  Day.dart is inspired by Day.js.
  Write with nearly the same API.
  Build on the top of the powerful DateTime class.
homepage: https://github.com/dayjs/day.dart
repository: https://github.com/dayjs/day.dart
issue_tracker: https://github.com/dayjs/day.dart/issues
documentation: https://github.com/dayjs/day.dart/blob/master/API.md

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  test: ^1.6.8
